### ISSUE TITLE
Unable to use [(ngModel)] in mat-autocomplete when ng-trim-value-accessor is used

### ISSUE THREAD

**Issue by lahiruchandima** [khashayar/ng-trim-value-accessor#22] opened 2018-10-01 12:05 UTC
When I try to add `[(ngModel)]` directive to mat-autocomplete, I get following warning.

> ERROR Error: More than one custom value accessor matches form control with unspecified name attribute

This warning gets fixed if I remove the `TrimValueAccessorModule` import to my module.

I can disable `TrimValueAccessorModule` for the mat-autocomplete by adding `class="ng-trim-ignore"` attribute to the input element of mat-autocomplete and fix the warning, but it would be better if `TrimValueAccessorModule` could work with mat-autocomplete without a problem.

**Comment by khashayar** [comment] 2018-10-01 12:10
Duplicate of #17 

It's an Angular limitation which doesn't allow to attach more than two custom value accessor to one form element.

**Closed by khashayar** 2018-10-01 12:10 UTC
